name: Actions CI

on: push

env:
  CUATRO_HEX_KEY: ${{ secrets.CUATRO_HEX_KEY }}

jobs:
  bless:
    name: Bless
    runs-on: ubuntu-16.04
    env:
      MIX_ENV: test

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Restore the deps cache
      uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-deps-${{ env.MIX_ENV }}

    - name: Restore the _build cache
      uses: actions/cache@v1
      with:
        path: _build
        key: ${{ runner.os }}-build-${{ env.MIX_ENV }}

    - name: Determine the elixir version
      run: echo "::set-env name=ELIXIR_VERSION::$(grep -h elixir .tool-versions | awk '{ print $2 }' | awk -F - '{print $1}')"

    - name: Determine the otp version
      run: echo "::set-env name=OTP_VERSION::$(grep -h erlang .tool-versions | awk '{ print $2 }')"

    - name: Setup Elixir and Erlang versions
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ env.ELIXIR_VERSION }}
        otp-version: ${{ env.OTP_VERSION }}

    - name: Fetch mix dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Compile dependencies
      run: mix deps.compile

    - name: Compile
      run: mix compile --warnings-as-errors --force

    - name: Coveralls
      run: mix coveralls

    - name: Check formatting
      run: mix format --check-formatted

    - name: Credo
      run: mix credo

    - name: Generate documentation
      run: mix docs
      env:
        MIX_ENV: dev

    - name: Determine the tag version
      env:
        GITHUB_REF: ${{ github.ref }}
      run: echo "::set-env name=TAG::$(echo "$GITHUB_REF" | awk -F / '{print $3}')"
      if: startsWith(github.ref, 'refs/tags/v')

    - name: Determine the repository name
      run: echo "::set-env name=REPOSITORY::$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}')"
      if: startsWith(github.ref, 'refs/tags/v')

    - name: Publish library
      run: mix hex.publish --yes --organization cuatro
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        MIX_ENV: dev
        HEX_API_KEY: ${{ secrets.HEX_PUBLISH_KEY }}

    - name: Notify ops channel of publish success
      run: |
        curl \
          -X POST \
          -H 'Content-type:application/json' \
          -d "{\"text\":\"hex package published for $REPOSITORY $(git tag -ln $TAG)\"}" \
          $SLACK_WEBHOOK
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        SLACK_WEBHOOK: ${{ secrets.OPS_CHANNEL_SLACK_WEBHOOK }}

# Generated by Elixir.Gaas.Generators.Simple.Actions.LibraryCi
